'("MultiProduct rebate"
 "Monthly fee"
 "ENBRIDGE"
 "Property Tax CITY OF OTTAWA"
 "Insurance OMA INSURANCE"
 "ATM withdrawal"
 "Mortgage payment"
 "Payroll Deposit CHEO"
 "Loan interest"
 "Payroll Deposit EORLA"
 "Online Banking payment"
 "Cheque"
 "INTERAC e-Transfer"
 "ATM deposit"
 "Online Banking transfer"
 "Contactless Interac purchase"
 "Online Banking loan payment"
 "Utility Bill Pmt OTTAWA WATER"
 "Loan proceeds"
 "Loan HONDA FINANCE"
 "Insurance SNLF ASSOC AFF"
 "Online Banking 3rd party deposit"
 "ATM Cash-back withdrawal"
 "Misc Payment CHEO LABORATORY"
 "ATM deposit")
